version: "3.9"

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/app
  
  php:
    build: ./services/php
    volumes:
      - ./app:/app
  
  mysql-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - ./mysql-data:/var/lib/mysql
  mysql-db2:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - ./mysql-data:/var/lib/mysql
  mysql-db3:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - ./mysql-data:/var/lib/mysql
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  node:
    build: ./services/node

volumes:
  mysql-data: {}